### ISSUE TITLE
Admin panel: Close the source for Laravel Nova or invest in open source tool?

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/campy-app#183]
This one will be a tough decision:
- Plans are that all CD contacts and processes will be centralized in Campy (future name: app)
- This means: Participants' signups, coach registration, newsletter signup, partner contacts -> everything will be in Campy
- To manage these information with a larger group of people ("Vorstände"), we will need a admin panel
- The most natural choice would be [Laravel Nova](https://nova.laravel.com/), a pwerful code-driven admin package
- The problem with Nova: We cannot release the source of the admin code
- Two possible solutions

## Use Nova but close the source to the public
- Nova is a feature-rich and well-documented package written by Laravel core developers
- Campy gets maintained by a small group of people (and this will likely not change soon)
- We could make the repo closed source and keep working in the same team on the code

## Stay open source and use Otter
- [Otter](https://github.com/poowf/otter) and [Sharp](https://github.com/code16/sharp) are promising open source alternatives but come nowhere near Nova in respect to features and documentation
- Using either of the both would mean a lot more work to get stuff done and also to invest in improving these tools (by contributing to their source code via PR)
- We would need to quickly get more people contributing to Campy (and the external packages), which only takes energy away from developing the core

I am strongly in favour of closing the source for Campy for the foreseeable future and use Nova.

What do you think, @Jubeki and @toorusr (as you are our main contributors)?

**Comment by Jubeki** [comment]
I am a fan of open source.
But I would look later into it.
Right now I am doing a list of what features should be done.
Maybe our website will be integrated into campy so that nothing needs to be done twice.

**Comment by minthemiddle** [comment]
Decision: Close the source to use Nova. Best tradeoff between loosing open source and getting features and documentation that is sustainable. Reasons were given

> Nova is a feature-rich and well-documented package written by Laravel core developers
Campy gets maintained by a small group of people (and this will likely not change soon)
We could make the repo closed source and keep working in the same team on the code

Source:  https://github.com/CodeDesignInitiative/campy-app/issues/183#issue-401766382
